// <auto-generated />
namespace SimplReaderBLL.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class fixedkeytypeofrssFeed : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fixedkeytypeofrssFeed));
        
        string IMigrationMetadata.Id
        {
            get { return "201303241506363_fixed key type of rssFeed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
