// <auto-generated />
namespace SimplReaderBLL.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Addedcalculatednubmeroffeeditems : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addedcalculatednubmeroffeeditems));
        
        string IMigrationMetadata.Id
        {
            get { return "201303301348332_Added calculated nubmer of feed items"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
