// <auto-generated />
namespace SimplReaderBLL.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Addeduserstatuses : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addeduserstatuses));
        
        string IMigrationMetadata.Id
        {
            get { return "201303282144549_Added user statuses"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
